language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    # Selftests
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-21.04
      name: "ppctests: ppc64le Ubuntu 21.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-16.04
      name: "ppctests: ppc64le Ubuntu 16.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=selftests SUBARCH=ppc64le IMAGE=ubuntu-21.04
      name: "selftests: ppc64le"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - mkdir -p $HOME/.ccache
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
