dist: trusty
sudo: false
language: c
compiler: gcc

addons:
  apt:
    packages:
    - flex
    - bison
    - sparse

os:
  - linux-ppc64le

branches:
  only:
    - ci-test

script:
  - export CROSS_COMPILE=
  - export ARCH=powerpc
  - export DEFCONFIG=ppc64le_defconfig
  - export KBUILD_OUTPUT=build
  - export JFACTOR=$(nproc)
  - export SILENT=0
  - export KBUILD_CHECKSRC=2
  - arch/powerpc/tools/ci/build.sh
